kind: Service
apiVersion: v1
metadata:
  name: pp-backend-service
  namespace: default
  labels:
    app: pp
    tier: backend
spec:
  ports:
    - protocol: TCP
      # The port this service will be available is on.
      # Must match frontend nginx conf file setting.
      port: 80
      # The container port the service will forward to.
      # Named in pod spec in deployment yaml.
      targetPort: app-port
  selector:
    app: pp
    tier: backend
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
