
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: project-perform
build:
  # defines where to find the Dockerfile build configurations at build time and where to push the resulting images
  artifacts:
  - image: pp-backend
    context: backend
  - image: pp-frontend
    context: frontend
  # use locally-installed build tool (Docker) to build
  local: {}
  tagPolicy:
    sha256: {}

# TO DO: instruct Skaffold to run container structure tests
# test:
#   - image: gcr.io/project-perform/xxx
#     structureTests:
#      - './structure-test/*'

deploy:
  kubectl:
  # defines the Kubernetes manifests to deploy on each run
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
# default configuration as above
- name: default
# TO DO: use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
