
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: project-perform
build:
  # Defines where to find the Dockerfile build configurations at build time and the resulting image names
  artifacts:
  - image: gcr.io/project-perform/pp-backend/development
    context: backend
    sync:
      manual:
        - src: 'dist/**/*'
          dest: /
  - image:  gcr.io/project-perform/pp-frontend/development
    context: frontend
    sync:
      manual:
        - src: 'dist/**/*'
          dest: /usr/share/www/
          strip: 'dist'
  # Defines the image tag
  tagPolicy:
    # Uses :latest as the tag
    sha256: {}
  # Use the locally-installed build tool (Docker) to build
  local: {
    # If not specified, push true only for remote clusters
    push: true
  }
deploy:
  # Set kube context to use the test cluster - must be started in advance
  kubeContext: gke_project-perform_europe-west2-c_ppk8es-cluster-test
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: project-perform
        chartPath: ../project-perform-k8es-cd/pp-chart
        valuesFiles:
          - ../project-perform-k8es-cd/pp-chart/values.yaml
        # Override keys in the values.yaml file
        artifactOverrides:
        # This replaces the equivalent .Values reference in 'image' in the deployment yaml files
          frontend.image: gcr.io/project-perform/pp-frontend/development
          backend.image: gcr.io/project-perform/pp-backend/development
    # Additional option flags that are passed on the command line to helm.
    flags:
      # 20200816 Helm v3.2.2 bug requires this flag or upgrade after change will fail - 'Service is immutable'
      upgrade: [ "--force=false" ]
portForward:
  # Forward frontend port 80 to localhost:8080
  # (localhost is seen as secure and avoids exception from Auth0)
  - resourceType: service
    resourceName: project-perform-pp-chart-frontend-service
    namespace: default
    port: 80
    address: 127.0.0.1
    localPort: 8080
  # Forward backend port 80 to localhost:8081
  - resourceType: service
    resourceName: project-perform-pp-chart-backend-service
    namespace: default
    port: 80
    address: 127.0.0.1
    localPort: 8081
