
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: project-perform
build:
  # Defines where to find the Dockerfile build configurations at build time and the resulting image names
  artifacts:
  - image: pp-backend
    context: backend
    sync:
      manual:
        - src: 'dist/**/*'
          dest: /
  - image: pp-frontend
    context: frontend
    sync:
      manual:
        - src: 'dist/**/*'
          dest: /usr/share/www/
          strip: 'dist'
  tagPolicy:
    dateTime: {}
  # Use locally-installed build tool (Docker) to build
  local: {
    # If not specified, push true only for remote clusters
    push: true
  }
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
  # Defines the Kubernetes manifests to deploy on each run
    manifests:
      - ./kubernetes-manifests/backend.service.yaml
      - ./kubernetes-manifests/frontend.service.yaml
      - ./kubernetes-manifests/backend.deployment.yaml
      - ./kubernetes-manifests/frontend.deployment.yaml
      - ./secrets/app.secret.yaml
      - ./kubernetes-manifests/gke.ingress.yaml
      # - ./kubernetes-manifests/nginx.ingress.yaml // Used with Minikube
portForward:
  # Forward frontend port 80 to localhost:8080
  # (localhost is seen as secure and avoids exception from Auth0)
- resourceType: service
  resourceName: pp-frontend-service
  namespace: default
  port: 80
  address: 127.0.0.1
  localPort: 8080
