kind: Deployment
apiVersion: apps/v1
metadata:
  name: pp-frontend-deploy
  namespace: default
  labels:
    app: pp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pp
      tier: frontend
  # Describes the pods that will be created.
  template:
    metadata:
      labels:
        app: pp
        tier: frontend
    spec:
      containers:
        - name: pp-frontend-deploy-1
          image: pp-frontend
          # Purely informational - name can be used in a service
          ports:
          - name: nginx-port
            containerPort: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # Note: If set to 'Always' will fail on Minikube
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
