kind: Deployment
apiVersion: apps/v1
metadata:
  name: pp-frontend-deploy
  namespace: default
  labels:
    app: pp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pp
      tier: frontend
  # Describes the pods that will be created.
  template:
    metadata:
      labels:
        app: pp
        tier: frontend
    spec:
      containers:
        - name: pp-frontend-deploy-1
          image: gcr.io/project-perform/nginx-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
