kind: Service
apiVersion: v1
metadata:
  name: testd
  namespace: default
  labels:
    run: testd
spec:
  ports:
    - protocol: TCP
    # The port this service will be available is on.
      port: 80
      # The container port the service will forward to.
      targetPort: 80
  selector:
    run: testd
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
