kind: Service
apiVersion: v1
metadata:
  name: pp-frontend-service
  namespace: default
  labels:
    app: pp
    tier: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - protocol: TCP
      # The port this service will be available is on.
      # External url comes in on this port.
      port: 80
      # The container port the service will forward to.
      # Named in pod spec in deployment yaml.
      targetPort: nginx-port
  selector:
    app: pp
    tier: frontend
  # NodePort is the required type for a Ingress Controller backend 
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
