kind: Deployment
apiVersion: apps/v1
metadata:
  name: pp-frontend-deploy
  namespace: default
  labels:
    app: pp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pp
      tier: frontend
  # Describes the pods that will be created.
  template:
    metadata:
      labels:
        app: pp
        tier: frontend
    spec:
      containers:
      - name: pp-frontend-deploy
        image: gcr.io/project-perform/pp-frontend:v1.0.0
        ports:
        - name: nginx-port
          # Frontend server must be open on this port
          containerPort: 80
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # Note: If set to 'Always' will fail on Minikube
        # 'Always' may avoid caching issues when making changes?
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
