apiVersion: v1
kind: Service
metadata:
  name: pp-frontend-service
  namespace: default
  labels:
    app: pp
    tier: frontend
  # annotations:
    # cloud.google.com/neg: '{"ingress": true}'
spec:
  # NodePort is the required type for a Ingress Controller backend
  type: NodePort
  ports:
    - protocol: TCP
      # The port this service will be available is on.
      # External url comes in on this port.
      port: 80
      # The container port the service will forward to.
      # Named in pod spec in deployment yaml.
      targetPort: nginx-port
  selector:
    app: pp
    tier: frontend
  sessionAffinity: None
  externalTrafficPolicy: Cluster
